{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quiz2_total_requests{method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[30m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "total req count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_req", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_express_req_res_time_bucket{route=\"/quiz2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  }
 ]
}
{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error/Warning Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app_name=\"quiz_backend\", level =~\"warn|error\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app_name=\"quiz_backend\", level=\"info\"} |= ``"
    }
   ]
  }
 ]
}
{
 "title": "PSQL",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "User", "label": "User", "query": "select username from users;" },
   {
    "name": "User_id",
    "label": "User_id",
    "query": "select id from users where username='$User';"
   }
  ]
 },
 "panels": [
  {
   "title": "All Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, username, email FROM users ;"
    }
   ]
  },
  { "title": "User Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Stats",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\ntotalgames as \"Games Played\",\r\npoint1 as \"Solo Points\",\r\npoint2 as \"Duel Points\"\r\nfrom basicprofile\r\nWHERE userid='$User_id ';"
    }
   ]
  },
  {
   "title": "Match Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\nsingle as \"Solo Count\",\r\ndouble as \"Duel Count\" \r\nfrom matchcount \r\nwhere userid='$User_id' "
    }
   ]
  },
  {
   "title": "Duel Stats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select win, loss, draw\r\nfrom resultsummary\r\nWHERE userid='$User_id' \r\n"
    }
   ]
  },
  {
   "title": "Friends",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select u.id, u.username \r\nfrom users u join friend f\r\non f.user2id=u.id\r\nwhere f.user1id = '$User_id'"
    }
   ]
  },
  { "title": "Games History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Solo history",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select \r\ngameid as \"Game ID\",\r\nresult as \"Points\"\r\nfrom sessionspec1\r\nWHERE userid='$User_id';"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\r\ns.game_id as \"GAME ID\",\r\nu.username as \"Against\",\r\nCASE \r\n  WHEN s.result = 2 THEN 'Lost'\r\n  WHEN s.result = 1 THEN 'Won'\r\n  ELSE 'Draw'\r\nEND AS \"Result\"\r\nfrom sessionspec2 s\r\njoin users u\r\non u.id=s.user2id\r\nWHERE s.user1id='$User_id';"
    }
   ]
  }
 ]
}